[package]
name = "merkle_trees"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
openzeppelin = "1.0.0"
starknet = ">=2.8.0"
alexandria_merkle_tree = { git = "https://github.com/keep-starknet-strange/alexandria.git" }

[dev-dependencies]
cairo_test = "2.11.1"

[[target.starknet-contract]]
casm = true # for deploying script
